# Install locally with:
# pre-commit install
# pre-commit install --hook-type pre-push

default_language_version:
  python: python3.12

repos:

  # Black - auto-formatting
  - repo: https://github.com/psf/black-pre-commit-mirror
    # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
    rev: 25.1.0
    hooks:
      - id: black
        name: Run Black formatting
        args: ["--config=pyproject.toml"]
        stages: [pre-commit]

  # Pylint - Python code linting
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.7
    hooks:
    - id: pylint
      name: Lint code with Pylint
      entry: uv run pylint
      args:
        [
          "--rcfile=pyproject.toml",
          "--fail-under=8.0",
          "--output-format=colorized",
          "--reports=false",
        ]
      language: system
      types: [python] # only run when python files where edited
      stages: [pre-commit]

  # isort - sorting package imports
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: Sort imports with isort
        args: ["--settings-path=pyproject.toml"]
        stages: [pre-commit]

  # File validation
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
        name: Remove trailing whitespace
        stages: [pre-commit]
    -   id: end-of-file-fixer
        name: Ensure file ends with a newline
        stages: [pre-commit]

  # Python Unit Tests
  - repo: local
    hooks:
    - id: pytest
      name: Run Pytest Unit Tests
      entry: uv run pytest
      args: ["tests"]
      language: system
      pass_filenames: false
      stages: [pre-push]



# Shellcheck - shell script linting
# ref: https://github.com/koalaman/shellcheck
  # -   repo: https://github.com/shellcheck-py/shellcheck-py
  #     rev: v0.10.0.1
  #     hooks:
  #     -   id: shellcheck
  #         name: Apply shellcheck
  #         types: [shell]  # Ensures it runs only on shell scripts
  #         # args: ["--severity=warning"]  # Optionally only show errors and warnings
